Repository ros2/rmw_connextdds, pull requests merged in 2021-04, with the labels that each got.

#28 Use rmw_qos_profile_unknown when adding entity to graph
  rmw_connextdds_common/src/common/rmw_graph.cpp
Labels: bug, galactic

#32 Backport #28 to branch `foxy`
  rmw_connextdds_common/src/common/rmw_graph.cpp
Labels: foxy

#34 Backport #25 to branch `foxy`
  rmw_connextdds_common/include/rmw_connextdds/static_config.hpp
  rmw_connextdds_common/src/ndds/dds_api_ndds.cpp
Labels: foxy, foxy-backports

#35 Backport #25 to branch `eloquent`
  rmw_connextdds_common/include/rmw_connextdds/static_config.hpp
  rmw_connextdds_common/src/ndds/dds_api_ndds.cpp
Labels: eloquent, eloquent-backports

#36 Backport #25 to branch `dashing`
  rmw_connextdds_common/include/rmw_connextdds/static_config.hpp
  rmw_connextdds_common/src/ndds/dds_api_ndds.cpp
Labels: dashing, dashing-backports

#37 Backport #23 and #33 to branch `foxy`
  README.md
  rmw_connextdds_common/src/common/rmw_type_support.cpp
Labels: foxy, foxy-backports

#38 Backport #23 and #33 to branch `eloquent`
  README.md
  rmw_connextdds_common/src/common/rmw_type_support.cpp
Labels: eloquent, eloquent-backports

#39 Backport #23 and #33 to branch `dashing`
  README.md
  rmw_connextdds_common/src/common/rmw_type_support.cpp
Labels: dashing, dashing-backports

#33 Correctly detect empty messages
  rmw_connextdds_common/src/common/rmw_type_support.cpp
Labels: bug, dashing-backports, eloquent-backports, foxy-backports, galactic

#41 Add environment variable to control override of DomainParticipantQos
  README.md
  rmw_connextdds_common/include/rmw_connextdds/context.hpp
  rmw_connextdds_common/include/rmw_connextdds/static_config.hpp
  rmw_connextdds_common/src/common/rmw_context.cpp
  rmw_connextdds_common/src/ndds/dds_api_ndds.cpp
Labels: dashing-backports, eloquent-backports, foxy-backports, galactic-backports, h-turtle

#47 Backport #41 to branch `foxy`
  README.md
  rmw_connextdds_common/include/rmw_connextdds/context.hpp
  rmw_connextdds_common/include/rmw_connextdds/static_config.hpp
  rmw_connextdds_common/src/common/rmw_context.cpp
  rmw_connextdds_common/src/ndds/dds_api_ndds.cpp
Labels: foxy, foxy-backports

#48 Backport #41 to branch `eloquent`
  README.md
  rmw_connextdds_common/include/rmw_connextdds/context.hpp
  rmw_connextdds_common/include/rmw_connextdds/static_config.hpp
  rmw_connextdds_common/src/common/rmw_context.cpp
  rmw_connextdds_common/src/ndds/dds_api_ndds.cpp
Labels: eloquent, eloquent-backports

#49 Backport #41 to branch `dashing`
  README.md
  rmw_connextdds_common/include/rmw_connextdds/context.hpp
  rmw_connextdds_common/include/rmw_connextdds/static_config.hpp
  rmw_connextdds_common/src/common/rmw_context.cpp
  rmw_connextdds_common/src/ndds/dds_api_ndds.cpp
Labels: dashing, dashing-backports

#25 Allow sharing DomainParticipant with C++ applications
  rmw_connextdds_common/include/rmw_connextdds/static_config.hpp
  rmw_connextdds_common/src/ndds/dds_api_ndds.cpp
Labels: dashing-backports, eloquent-backports, foxy-backports, galactic-backports, h-turtle

#43 Improved conversion of time values between ROS and DDS formats
  rmw_connextdds_common/src/common/rmw_impl.cpp
Labels: galactic, h-turtle

#53 Always modify UserObjectQosPolicy regardless of override policy
  rmw_connextdds_common/src/ndds/dds_api_ndds.cpp
Labels: dashing-backports, eloquent-backports, foxy-backports, galactic-backports, h-turtle
